name: otohidroliccylinder
description: Hidrolik Silindir TasarÄ±m UygulamasÄ±
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.1
  printing: ^5.13.4
  share_plus: ^10.0.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
